### ISSUE TITLE
Turn Order Customizations

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#154]
- [ ] `setActionPlayers` option that allows others to play, but following a turn order (not simultaneously).
- [ ] Retire the Pass move. It's better to just document a pattern on how to implement passing or convert it to an event.

**Comment by Stefan-Hanke** [comment]
OK, let's assume we've got a Dominion implementation and want to make Militia work. For this, we'd need the first bullet point. As far as I've understood the new API, we'd need an event that must currently be directly implemented in `FlowWithPhases`, since there is currently no possibility to have events defined by a Game.

If that event existed, a game could dispatch a call to it which would be triggered during the `update` call. That event (_changeActionPlayers_ or something like that) would need the actual players that ought to perform a move.

Did I get anything wrong?

**Comment by nicolodavis** [comment]
Yes, that's correct.

**Comment by Stefan-Hanke** [comment]
Since this allows concurrent state modifications, we'd need a way to reconcile state on a client with one that is `sync`ed. I don't know whether it's a good idea to let the game handle that process?

_Sidenote about order of players to take actions_: Actually, Dominion must enforce an order of action players since in case of that _Militia_, dropping cards could trigger e.g. _Marktplatz_ (don't know its english name), which may give you a _Gold_, which you don't when the pile is empty. So it's not the best example to choose... sigh.

**Comment by nicolodavis** [comment]
What concurrent state modification are you referring to?

**Comment by Stefan-Hanke** [comment]
The kind of modification where two states need to be merged somehow. E.g. two players simultaneously click on _Drop Card_, or one player is selecting cards to drop whereas the other one already has selected etc.

**Comment by nicolodavis** [comment]
That's already taken care of via the stateID mechanism is it not?

**Comment by nicolodavis** [comment]
An unsynced client cannot make a move basically.

**Comment by Stefan-Hanke** [comment]
Ah, maybe I don't know the specific multiplayer implementation. I'd like to avoid the case where one player loses part of his move because another is faster and comitted his...

**Comment by nicolodavis** [comment]
That will only happen if the user plays before the update caused by the other players reaches them, i.e. will only be seen if there is noticeable network lag. Maybe we can build a mechanism in the future to perform a true merge, so that an out of date client can be usable in some cases, but this is what we have right now.

**Comment by nicolodavis** [comment]
We might have to provide a hook to allow the game developer to specify how the stateID should change, and they could use a major.minor version system to indicate which state updates break old clients and which ones can tolerate a move from a client that hasn't seen the most recent state.

**Comment by titanxxh** [comment]
The Events API is still under development? No docs for it, right?

**Comment by nicolodavis** [comment]
There is a pending PR to add some documentation. I'm just waiting to get some time to add some interactive examples as well before I get that in.

**Comment by titanxxh** [comment]
Actually, I have a question about the best case for Phase. I’d like to know which one below is the best practice? 
1. Game is divided into different phases. In each phase players can take their turns one by one. For example, Agricola game can have setting, drafting, round, harvest... phases.
2. The turn of a player can divided into small phases. Let’s take Agricola for example again, one can do many Moves before he confirms to end his turn. He can click the “Plow and Sow” action, then enters into a “Plow” phase, in which he can only plow a field on his farm space or undo his decision or confirm to end this “Plow” phase. After that, he enters a “Sow” phase.

**Comment by nicolodavis** [comment]
@titanxxh An easy way to fix your problem would be for the framework to not accept `endTurn` from any player other than `currentPlayer`.

**Comment by titanxxh** [comment]
But this will not solve the `endPhase` triggered in one player's moves problem.

**Comment by nicolodavis** [comment]
But that's actually necessary in most cases (and in your case it doesn't actually matter if we don't allow the subsequent `endTurn`, correct?).

**Comment by Stefan-Hanke** [comment]
Ad retiring Pass: do you have any specifics in mind? It looks like a useful turn order implementation.

**Comment by nicolodavis** [comment]
Now that we're storing [stats](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L548) about who has played this turn / phase, and even exporting bits like `allPlayed`, I'm wondering if we should just document a simple pattern on how to implement passing.

The other option would be to make it an event, but I'd like to limit the number of events if possible (i.e. let's go this route only if it's that much simpler to use over implementing your own).

I don't have a clear idea of which option is best yet, so we have some exploring to do.

**Comment by nicolodavis** [comment]
Closing this in favor of #477 and #478.
