### ISSUE TITLE
Phases - Events Repeating...

### ISSUE THREAD

**Issue by RGBKnights** [nicolodavis/boardgame.io#258]
I have talked to you already on chat about this issue and based on our talk we both think it is a bug if so here are the details... I set up a game to use phases (in my case: Action, Movement, Reaction, & Maintenance. I added all the override methods for onPhaseBegin, onPhaseEnd, onTurnBegin, onTurnEnd, & onMove. I did one thing in all of these methods which was to console.log the name of phase, the name of the event, and the ctx.currentPlayer. All of these methods based on your documentation should be run on the server. 

This is where I get the 1st issue. I see in the console of the browser output for Action:onTurnBegin() & Action:onPhaseBegin. As well as the ctx.currentPlayer are both 0 even though I have 2 boards with the playerId parameter set. for example [phase:event() player]:

```javascript
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
```
I also see that repeated on the server logs:

```javascript
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
```

But in addition to the above, I get that block repeated again and again. It seems any time I use the Debug view to change the player. below is the log from my going through phases use the skipPhase option in the debug view.

```javascript
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Action:onPhaseEnd() 0
Movement:onPhaseBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Movement:onPhaseEnd() 0
Reaction:onPhaseBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Reaction:onPhaseEnd() 0
Maintenance:onPhaseBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Maintenance:onPhaseEnd() 0
Action:onPhaseBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Action:onTurnEnd() 0
Action:onTurnBegin() 1
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
```

The really interesting weird part is it always seems to be the 1st phase that has this issue and it always seems to be supply player 0.  We can see there are "Real" events in the log with the corrcet values for event and player. for example:

```javascript
Action:onPhaseEnd() 0
Movement:onPhaseBegin() 0
...
Movement:onPhaseEnd() 0
Reaction:onPhaseBegin() 0
...
Reaction:onPhaseEnd() 0
Maintenance:onPhaseBegin() 0
...
Action:onTurnBegin() 1
```

As I normally do (like last time) I tried to track down this issue to source/root with no success.
As well you ask for Repo to show you this behaviour I have created one @ the following branch
https://github.com/RGBKnights/Lusus/tree/RGB-TestForIssue258

Like last time you will need to run the server and client:
npx babel-node --presets zero .\src\server\app.js
npm run start

**Comment by Stefan-Hanke** [comment]
```javascript
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
```

This is OK. You see this two times because there are two players with separate views. For both views, the `currentPlayer` is the 0th one. Granted, without more trace output this looks weird. How about

```javascript
Creating Client for Player 0
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
Creating Client for Player 1
Setup() 0
Action:onPhaseBegin() 0
Action:onTurnBegin() 0
```
Maybe we can update #253 to not only provide error logging but a sort of tracing s.t. you can understand what's happening without debugging source code.

**Comment by RGBKnights** [comment]
I understand the sequence, what I believe is wrong is that is it showing up on the browser. Based on your documentation the onPhaseBegin / onTurnBegin should only happen on server yet there is output in the console.log for the browser.

**Comment by Stefan-Hanke** [comment]
I assume you're refering to the last paragraph [here](https://github.com/google/boardgame.io/blob/master/docs/phases.md). Granted; this could be less specific about where code is actually run. There is also the concept of an _optimisticUpdate_ that could play a role here, too.

The one main point is that in a game using a server, the latter has the last word always.

**Comment by RGBKnights** [comment]
Yes, that is what I am referencing and it holds turn for all functions but onTurnBegin and the onPhaseBegin of the 1st phase.

**Comment by Stefan-Hanke** [comment]
You will find that every time the reducer is created, it will call into the game's provided methods like observed ([setup call](https://github.com/google/boardgame.io/blob/master/src/core/reducer.js#L40), and the [begin methods as part of flow init](https://github.com/google/boardgame.io/blob/master/src/core/reducer.js#L64)). This is due to the reducer needing some initial state to work on, and this is the way it's done atm.

Two places:
* At Client: Client creation [here](https://github.com/google/boardgame.io/blob/master/src/client/client.js#L102)
* At Server: Client makes a move [see here](https://github.com/google/boardgame.io/blob/master/src/server/index.js#L45) - the game reducer is recreated every time.
* At Server: Client syncs [here](https://github.com/google/boardgame.io/blob/master/src/server/index.js#L126)

To mitigate the initial calls, we'd have to have a _gameStart_ event, and the initial state would have to be a dummy one, and must be ignored by `setup` and `on(Turn|Phase)Begin`.
Or we accept that the reducer is something that just can be created anywhere (with all consequences).

**Comment by nicolodavis** [comment]
There has been some talk of wanting a "start game" event for other reasons as well. I think it will be a natural follow up to the lobby implementation being developed. At that point creation of a reducer shouldn't result in any of the initialization code being run.

**Comment by Stefan-Hanke** [comment]
I've not looked at the lobby code - I'd create a separate issue?
For the time being, we could introduce the _gameStart_ event and directly process one, that way the observed reducer behaviour should stay unchanged.

**Comment by nicolodavis** [comment]
We can introduce a gameStart event right away. The problem is I'm not sure where we are going to trigger it.

The reason I mentioned the lobby is that it provides a very natural place to start a game. All the players join and the game creator can actually hit a button that says "start game", or the game can start automatically as soon as everyone joins.

At the moment games are created in an ad-hoc fashion. We could dispatch the gameStart event right around [here](https://github.com/google/boardgame.io/blob/master/src/server/index.js#L139), but I'm guessing that code will be gone once the lobby implementation is in.

**Comment by Stefan-Hanke** [comment]
So currently, all games are in an _autoStart_ mode that will directly trigger initialization, and if not, the reducer may not perform initialization. That way, e.g. the examples could run with _autoStart=true_, and using the _gameStart_ event is an explicit opt-in. However, I think the final implementation should be the other way round...

I wonder whether the server should know game instances that are not started at all. Otherwise we'd need a way to know game instances that are not started yet.
