### ISSUE TITLE
log message when move is ignored due to lack of return

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#286]
No messaging here can lead to people wondering why a particular move isn't working (if they forgot to return `G`).

**Comment by Stefan-Hanke** [comment]
_Here_? Where?

**Comment by nicolodavis** [comment]
I meant "in this situation" :) I'm thinking that we should just add a simple `logging.info` in reducer.js whenever it encounters a move that returns `undefined`.

**Comment by Stefan-Hanke** [comment]
Calls to `logging.error` have been added to `master.js`, and it looks somewhat similar. In the latter, the game reducer is created also. Intuitively I cannot make sense of these checks being duplicated. Maybe the call to `dispatch` hits the network because of attached middlewares?

What about dropping the checks and moving the log calls to the game reducer itself?

**Comment by nicolodavis** [comment]
This is now obsolete after the addition of Immer.
