### ISSUE TITLE
Curious Flow: Second phase's onTurnBegin() is not calling

### ISSUE THREAD

**Issue by ybbarng** [nicolodavis/boardgame.io#394]
Hello, I'd like to use your impressive framework, but I met a strange situation.

Here's my simplified code:
https://github.com/ybbarng/boardgame-io-test/blob/master/src/App.js

In phase1, each turn is automatically ended because endTurn() is called in onTurnBegin().
Because the phase1's TurnOrder is ONCE, the phase will be moved to next phase2.
At this time, onTurnBegin() of phase2 is not calling.
I hope someone figure out my mistake or explain why this happens.

Context when it stuck,

The log of console:
```
phase1 onPhaseBegin
phase1 onTurnBegin 0
phase1 onTurnEnd 0
phase1 onTurnBegin 1
phase1 onTurnEnd 1
phase1 onPhaseEnd
phase2 onPhaseBegin
```

The debug pannel:
```
G: {}
ctx: {
  "numPlayers": 2,
  "turn": 2,
  "currentPlayer": "0",
  "actionPlayers": [
    "0"
  ],
  "currentPlayerMoves": 0,
  "playOrder": [
    "0",
    "1"
  ],
  "playOrderPos": 0,
  "stats": {
    "turn": {
      "numMoves": {},
      "allPlayed": false
    },
    "phase": {
      "numMoves": {},
      "allPlayed": false
    }
  },
  "allPlayed": false,
  "phase": "phase2",
  "prevPhase": "phase1",
  "allowedMoves": null
}
```

**Comment by nicolodavis** [comment]
This is a bug that will be fixed as part of the Phases overhaul described [here](https://github.com/nicolodavis/boardgame.io/issues/367).

**Comment by nicolodavis** [comment]
I'm working on this presently, so it should be fixed in the next couple of weeks or so.

**Comment by JosefKuchar** [comment]
Any updates on this or the phases overhaul?

**Comment by nicolodavis** [comment]
Still about a couple of weeks out.

**Comment by gadamgrey** [comment]
Hi, I am running into a similar issue and was wondering if the new phases structure will be coming soon.  Thanks in advance!

**Comment by nicolodavis** [comment]
It's ready in the phases-overhaul branch of you'd like to test it.  I need to work on the documentation and polish it a bit before I release it.

**Comment by delucis** [comment]
@gadamgrey Do you have some code you could share?

Usually, `ctx.currentPlayer` should change when a turn ends (as long as your turn order isn’t set to something that prevents that).

With the `phases-overhaul` branch, the game you describe might look something like this (N.B. some of this API may change, see for example #445 and #446):

```js
import { ActivePlayers } from 'boardgame.io/core'

const game = {
  phases: {
    setup: {
      start: true,                              // the game should start in this phase
      turn: {
        activePlayers: ActivePlayers.ALL_ONCE   // all players can play once
      },
      moves: {
        setupMove: (G, ctx) => {},
        pass: G => G
      },
      endIf: (G, ctx) => ctx.activePlayersDone, // end phase when each player has played
      next: 'main',                             // move to “main” stage on end
    },

    main: {
      turn: {
        endIf: (G, ctx) => ctx.numMoves >= 1    // end turn after one move
      },
      moves: {
        // ...
      },
    },
  },
}
```

The `setup` phase makes use of the new `activePlayers` API to allow all players to play (in any order). The `ALL_ONCE` preset removes each player from `activePlayers` as each plays, so we can check `ctx.activePlayersDone` in `setup.endIf` to decide when to end the phase.

During the `main` phase, we check if a move has been made in `main.turn.endIf` and end the turn if it has. Alternatively, you could also check for some specific state before ending the turn or call `events.endTurn` from a move to end the turn. Because `main.turn.order` isn’t set, `boardgame.io` will default to `TurnOrder.DEFAULT`, which will increment `ctx.currentPlayer` at the end of each turn.

Again, this API is still in development and might change, but hope this helps!

**Comment by nicolodavis** [comment]
@delucis You can use `moveLimit: 1` for the "main" phase to make the code more idiomatic:

```js
import { ActivePlayers } from 'boardgame.io/core'

const game = {
  phases: {
    setup: {
      start: true,                              // the game should start in this phase
      next: 'main',                             // move to “main" after this phase

      turn: {
        activePlayers: ActivePlayers.ALL_ONCE   // all players can play once
      },

      moves: {
        setupMove: (G, ctx) => {},
        pass: G => G
      },

      endIf: (G, ctx) => ctx.activePlayersDone, // end phase when all players have played

    },

    main: {
      turn: {
        moveLimit: 1    // end turn after one move
      },

      moves: {
        // ...
      },
    },
  },
}
```

@gadamgrey What errors are you seeing when you run `npm -i git://..`?

**Comment by delucis** [comment]
@gadamgrey The library needs building if you’re using a git clone:

```sh
git clone https://github.com/nicolodavis/boardgame.io.git
cd boardgame.io
git checkout phases-overhaul
npm i
npm run prepack    # builds and exposes bindings
npm link
cd /path/to/project
npm link boardgame.io
```

Might be wise to run `npm un boardgame.io` in your project before linking just in case, but I think the above should work.

**Comment by delucis** [comment]
@gadamgrey I think the error is because `rollup` isn’t available globally. To avoid the global installs you could use [`npx`](https://nodejs.dev/the-npx-nodejs-package-runner).

**Comment by nicolodavis** [comment]
If you ever want to subdivide a turn into multiple "phases", you should use `stages`.  `phases` are for general game phases inside which multiple turns are played.  `stages` are different parts of a single turn.

```js
import { ActivePlayers } from 'boardgame.io/core'

const game = {
  turn: {
    activePlayers: {
      currentPlayer: 'A',  // put the player in Stage A at the beginning of the turn
    },

    stages: {
      A: {
        moves: {
          moveA: (G, ctx) => {
            ...

            // move the player to Stage B.
            ctx.events.setActivePlayers({ currentPlayer: 'B' });
          },
        },
      },

      B: {
        moves: { ... },
      },
    }
  }
}
```

**Comment by gadamgrey** [comment]
Are there hooks for onStageBegin and onStageEnd like there are for phases?  For some stages I will need the game to do some automated activities that can move things along without a player making any moves (like drawing a hand, or applying effects that trigger at different points in the game).

**Comment by nicolodavis** [comment]
I deliberately left these out because of the following reason:

1. turn.onBegin and phase.onBegin refer to single events that happen deterministically, and the game can only be in one state or turn at a given time.

2. When it comes to stages, multiple stages can be active at the same time, and at that point the order in which these hooks trigger can matter, which can confuse users.

We can explore doing something like always triggering them in increasing order of playerID or something like that, but in general I'd prefer to leave them out altogether if possible.

**Comment by nicolodavis** [comment]
Closing this now that v0.33 is out.  Feel free to reopen if you find that the issue you're dealing with still persists.
