### ISSUE TITLE
setActivePlayers function in onBegin hooks only work once

### ISSUE THREAD

**Issue by Pong420** [nicolodavis/boardgame.io#487]
```js
{
  turn: {
    onBegin: (G, { numPlayers, currentPlayer, events }) => {
      const value = {};
      for (let i = 0; i < numPlayers; i++) {
        value[i] = currentPlayer === String(i) ? 'main' : 'others';
      }
      events.setActivePlayers({ value });
      return G;
    }
  }
};
```

in the next turn `ctx.activePlayers` will be null

**Comment by delucis** [comment]
This might be related to #482. I haven’t tested if `setActivePlayers` works in `onBegin`.

That said, at least for your example, you could achieve this more simply like this:

```js
{
  turn: {
    activePlayers: { player: 'main', others: 'others' }
  }
}
```

**Comment by Pong420** [comment]
it works, thanks so much

**Comment by nicolodavis** [comment]
I don't think #482 is involved here (that bug only kicks in if an event does something like ending the turn (or phase) which further triggers an `onEnd` that contains another event).

@delucis has already pointed out the more idiomatic way of doing this, but I'm still curious why the original example does not work.

**Comment by Pong420** [comment]
For your reference,
I have try `setActivePlayers` in below example.
```js
{
  onBegin: (G, ctx) => {
    ctx.setActivePlayers({ player: 'main', others: 'others' });
  };
}
```
The player who last takes the move in the previous phase is in `main` stage but not the `ctx.currentPlayer`

**Comment by delucis** [comment]
Just a quick note to say I ran into this myself today. I had a situation where I wanted to configure turn active players conditionally, based on game state. In a simplified form:

```js
turn: {
  onBegin: (G, ctx) => {
    if (G.flag) ctx.events.setActivePlayers(/*...*/)
  }
}
```

But this always results in `ctx.activePlayers === null`

I guess this would also come up if you wanted to pass different values to `setActivePlayers` based on some game state.

I’ll try to dig into why this is happening, but if you have any ideas @nicolodavis, let me know!

**Comment by delucis** [comment]
So, the events flow is a nightmare to debug, but I can confirm what @Pong420 reported, that the `playerID` used by events dispatched in `turn.onBegin` seems to be stale. If `currentPlayer` has been incremented, `playerID` here will still be `currentPlayer - 1`.

I _think_ the bug is that `playerID` here is provided by the `Events` class when it creates the event action:

https://github.com/nicolodavis/boardgame.io/blob/9d74966ad4656021c971b012e59973ebedcc618b/src/core/events.js#L62

Prior to `StartTurn`, which dispatches `turn.onBegin`, [`UpdateTurnOrderState`](https://github.com/nicolodavis/boardgame.io/blob/9d74966ad4656021c971b012e59973ebedcc618b/src/core/turn-order.js#L254) moves `ctx.playOrderPos` and `ctx.currentPlayer` along.

A call to `setActivePlayers` (or other `playerID`-based events) in `turn.onBegin` should have a `playerID` that reflects the new `ctx.currentPlayer`, but I guess because it’s still being processed by the `Events` instance created in the previous turn, it doesn’t.

I’m still not quite clear how the context enhancers work, but I’m guessing the relevant one here is created in the reducer:

https://github.com/nicolodavis/boardgame.io/blob/9d74966ad4656021c971b012e59973ebedcc618b/src/core/reducer.js#L83

Maybe this also explains why sometimes these events are producing `null` `activePlayers`, if the ID is mismatched and the reducer ignores the event?

**Comment by nicolodavis** [comment]
Thanks for looking into this!  A bit busy this week, so will take a look over the weekend.

**Comment by nicolodavis** [comment]
Just to confirm, we still don't know what the cause of the original problem (of `activePlayers` being `null` on the second turn) is, correct?

**Comment by delucis** [comment]
Correct, but I’m almost certain it is in fact #482.

I think the `setActivePlayers` in `turn.onBegin` is not being processed because the turn was ended via a move. In the absence of `turn.activePlayers`,  `activePlayers` is reset to `null` at the start of a turn and then because the events called in the `onBegin` function are never processed, `activePlayers` remains `null`.
