### ISSUE TITLE
in redacted-move example second player clicks are ignored

### ISSUE THREAD

**Issue by amitport** [nicolodavis/boardgame.io#546]
Hi,

this seems to like me like more than a bug in the example, since the game object looks OK (using  `TurnOrder.ANY `) (version 0.37.1)

**Comment by nicolodavis** [comment]
Ah, `TurnOrder.ANY` was deprecated a while back.

Turns now just specify how the turn moves between players (and there can only be exactly one player who owns the turn at a given time.

You can specify other players that may play on your turn, though.  In this case, this is achieved by:

```js
turn: {
  activePlayers: ActivePlayers.ALL,
}
```

Fixed in https://github.com/nicolodavis/boardgame.io/commit/7c65046beb2835c3c63fd55e50e7d4ae8fe36dbe
