### ISSUE TITLE
onBegin for stages?

### ISSUE THREAD

**Issue by pardahlman** [nicolodavis/boardgame.io#561]
Is there any particular reason why phase and turn has a `onBegin` callback, whereas stage - that is similar in many ways, hasn't?

**Comment by delucis** [comment]
Stages are a bit different because multiple players can be in different or the same stage. For example, you might use stages to have the current player in one stage and the other players in a second stage. Assuming more than one player is put in the same stage, how would `onBegin` work? Should it be called once for each player? Once for each stage type? In what order would these calls happen?

Given this potential complexity, the decision was not to have an `onBegin` for stages.

**Comment by pardahlman** [comment]
I think it would make sense for `onBegin` to be called for each player entering a stage, each time they enter a stage. IMO, the fact that multiple players can be in multiple stages can be considered  a side note to an overall design: "whenever a player enters a phase, turn or step `onBegin` is called"

**Comment by delucis** [comment]
It’s possible, but it’s very easy to create bugs with this approach:

```js
// in game config
stages: {
  A: {
    onBegin: (G, ctx) => {
      G.someCount += 1
      G.stagePlayer = ctx.playerID
    }
  }
}

// somewhere in a move
events.setActivePlayers({ all: 'A' })
```

How much would `G.someCount` increment? (It depends on how many players there are.) Who would be `G.stagePlayer`? (It depends on which order the players get iterated through, which can vary on different engines when iterating through object keys.) Obviously these are user bugs and you could write this code in some way to avoid this kind of thing, but it is still bug-prone because the `onBegin` functionality becomes dependent on how the stage is instantiated elsewhere.

What’s your use case? Perhaps there’s a way to implement some version of `onBegin` if there’s a compelling use or perhaps there’s a straightforward way to achieve it using another approach.

**Comment by pardahlman** [comment]
You can indeed get unexpected game state when changing "global" properties for just the reasons you point out. I'm thinking of scenarios where you want to update player state (slices of the state associated with the specific player).

In my scenario, a turn consists of multiple stages, and the player state updates as the player progresses through the turn. For example a card becomes untapped in the second stage of the turn.

**Comment by delucis** [comment]
One approach you could use is have internal `moveToStageX` “moves”, which you use wherever you current call `setActivePlayers`:

```js
function moveToStageX(G, ctx) {
  // do stage set-up, mutating G
  // ...
  ctx.events.setActivePlayers({ currentPlayer: 'X' })
  // or ctx.events.endStage() depending on stage config
}
```

**Comment by pardahlman** [comment]
The code that handles the progression through the different stages is generic and only acts based on a dynamic list of the current "step order" in the turn. It could perhaps be updated to call some stage specific callback, but I'm not thrilled about it, as I would have different ways to do `onBegin` logic.

Anyways, thanks a lot for your input 👌 . If the collective decision is to not support `onBegin` in stages, I will have to look into alternative approaches 👍
