### ISSUE TITLE
Automatic Phase

### ISSUE THREAD

**Issue by dondragon2** [nicolodavis/boardgame.io#599]
I am trying to create a simple multiplayer card game with 2 phases. First phase the players select a card (Jack, King or Queen). Once selection is done then the second phase begin. The second phase a dealer (bot) automatically flips card from the deck at some interval (e.g. every 3 secs) until a card appears that matches the player. It is a simple game. 

I am not seeing anything from the documentation that I should use to get this "automatic" dealing with interval. Can someone point me in the right direction or how would I go about doing this?

**Comment by nicolodavis** [comment]
As far as the game state is concerned, you can just deal all the cards instantly (until a match is found) and then animate the draw with the 3-second interval on the client.

There exists no mechanism to trigger a state update on the server at a particular interval at the moment.

**Comment by dondragon2** [comment]
At what part of the phase do i do this "you can just deal all the cards instantly"? If I put it in the `onBegin` in the next phase it just loops (deals) but the state is not updated until the end. So i am not able to see the changing state until the end.

**Comment by delucis** [comment]
I would model this something like the following.

#### The game state `G`
```js
pickedCard: null | cardType
deck: [cardType, cardType, ...]
flippedCards: null | [cardType, cardType, ...]
```

#### The move
```js
pickCard: (G, ctx, card) => {
  G.pickedCard = card
  const firstMatch = G.deck.findIndex(card)
  G.flippedCards = G.deck.slice(0, firstMatch + 1)
  G.deck = G.deck.slice(firstMatch + 1)
}
```

#### UI
On the client you watch `G.flippedCards` and when it goes from `null` to an array, you trigger your animation, one by one through the array of cards.

No need for bots or phases in this implementation, it’s just a single move. Of course your actual use case may be more complex — maybe you need an additional move to trigger the next turn (returning cards to the deck & shuffling them, resetting `flippedCards` to null), or want to end the game — but this general approach should be adaptable to these more complex uses.

**Comment by dondragon2** [comment]
@delucis thanks for your comments but I still don't see how the state would be updated incrementally. It just seems, based on your code, that the player picks a card and then we find a match in the deck then finish. Or is it that you are suggesting that this `pickCard` would be triggered every time by some player action? In that case, that is not what I was looking for.

What I wanted was the player to pick a card then when complete the loop begins to "find a card" from which we can animate the change of that state.

**Comment by dondragon2** [comment]
This is what I am doing currently but I am sure it is not correct. It just seems "Hacky" and i am not sure how this would work in a multiplayer scenario.

in the board.js I have
```
 state = {
        dealt: 1
    };

...

 <Card 
                             key={`${card.face}${card.suit}`} 
                             card={card}
                             onClick={() => {
                                 this.props.moves.SelectCard(card.face);
                                 this.props.events.endPhase();
                                 this.setState({ dealt: 1 });
                                 this.deal();
                                }}
                             />

...
 deal = () => {
        setTimeout(() => {    
            this.props.moves.Deal()
            this.setState({ dealt: this.state.dealt + 1 });
            if (this.state.dealt < 48) {  
               this.deal(); 
            }
         }, 500);
     
    }
```

**Comment by delucis** [comment]
> It just seems, based on your code, that the player picks a card and then we find a match in the deck then finish.

Yes, that’s correct. Basically, the idea is to separate game state (which maybe is persisted to a database etc.) from UI state (which is a visual representation of the game progress to a human user).

In a real game, each card is dealt one by one, but in a digital version, we can make it look like that’s what’s happening without actually storing each intermediate step. This is what I meant by having the UI react to `flippedCards` and animate them one by one. The user still sees the gradual reveal, without the complexity of firing off a move every few seconds.

Your approach could also work, but consider the following:

- If the client is refreshed or closed/reopened while dealing, should `deal` continue? How would you manage that?
- If using a server/database, do you _need_ to store every card flip, processing an action and writing to the database every few seconds?

In general I try to think of this as 1 move = 1 user action, but of course you can also code timers etc. into your client, it’s up to you.

For React, in order to render your cards one-by-one, you could do something like this:

```jsx
import React, { useEffect, useState } from 'react'

function FlippedCards ({ flippedCards }) {
  const [revealedCards, setRevealedCards] = useState([]);

  useEffect(() => {
    if (!flippedCards && revealedCards.length > 0) {
      // clear revealed cards as soon as `flippedCards` turns null
      setRevealedCards([]);
    } else if (flippedCards && flippedCards.length > revealedCards.length) {
      // flippedCards has more cards than the ones revealed to user
      const timer = setTimeout(() => {
        setRevealedCards([...revealedCards, flippedCards[revealedCards.length]])
      }, 1000);
      // return a clean-up method to cancel the timeout if needed
      return () => clearTimeout(timer);
    }
  }, [flippedCards, revealedCards]);

  return (
    <div>
      {revealedCards.map(card => <Card key={card} />)}
    </div>
  )
}
```

This is a little simple and doesn’t do any animation, etc. You might want to check out React Spring’s [`useTransition`](https://www.react-spring.io/docs/hooks/use-transition) or [React Transition Group](https://github.com/reactjs/react-transition-group), which provide some nice wrappers for this kind of staggered reveal of arrays of data.
