### ISSUE TITLE
Best way to delay state change

### ISSUE THREAD

**Issue by janKir** [nicolodavis/boardgame.io#607]
I am not quite sure how specific my question is to this library or if it might rather belong to Stackoverflow. But in case there are some boardgame-specific aspects I'm asking here.

I'm working on a React-based card game where some parts of the game state are reset at the end of a phase (but also during a phase e.g. when a trick is completed). Let's say the last player plays a card to the trick (using the `play` move) and the trick is now complete and can be reset for the next trick. Logically everything works correct, however, I'm looking for a way to delay the reset of the trick for a couple of seconds so players have actually the chance to see the last card and it won't disappear immediately. And I don't know how this can be approached best. 

I already tried to put the `G.trick = null` statement inside a `setTimeout()` which led to an error, probably due to the way boardgame wraps those move functions and processes changes in the game state.
The other way I can think of is to handle the state updates inside react and delay them there. Either in each component separately or in a global react state. I guess there might be others before me who had this use case in react, but I don't know if any recommended design patterns exist.

**Comment by delucis** [comment]
Yes, you should do this on the React side of things — watch the state changes in your React props and when `G.trick === null`, wait before propagating it. It’s a little tricky to handle — I still haven’t found a really elegant way of handling this kind of imperative event queuing in React’s declarative approach, but it’s definitely something that the UI layer should handle rather than trying to delay the move or whatever.

**Comment by janKir** [comment]
Thank you! I will look into it.
