### ISSUE TITLE
Rooms for different games returned when listing specific game rooms

### ISSUE THREAD

**Issue by Bombasarkadian** [nicolodavis/boardgame.io#620]
There seems to be a bug with listing game rooms when server supports multiple games. There is a room returned for each game type, even though request specifies a game name when fetching rooms.

Steps to reproduce:
1. Define multiple games
2. Run application in multiplayer with remote master
3. Create new room for one of the games (via API or with lobby)

Expected behavior:
One new room for selected game is visible.

Actual behavior:
New room for every game is visible.

![Kapture 2020-04-13 at 14 24 39](https://user-images.githubusercontent.com/2972266/79120171-88150e80-7d92-11ea-8471-8f9f7dc8ac6c.gif)

Here's the repository with the minimal setup required to reproduce this bug: https://github.com/Bombasarkadian/boardgame.io-multiple-games-bug
Run server with `node -r esm src/server.js` and client with `npm start`.

EDIT:
It seems like the issue is with rooms listing, not rooms creation. I'll prepare a fix soon

**Comment by cowic** [comment]
I just stumbled about the exact same issue some days ago and tracked it down to

`const gameList = await db.listGames(gameName);`
 (in src/server/api.ts line 131)

The contract with db api requires an object with property "gameName" instead of a string. So this line should be:
`const gameList = await db.listGames({gameName});`

**Comment by oliw** [comment]
Same! Thanks putting the PR out
